### ISSUE TITLE
Connect to Compose DB

### ISSUE THREAD

**Issue by Katyadelarosa** [DrMongo/DrMongo#101]
Hi guys Im trying to connect to a compose DB but it seems like I can't so, this is how I have my credentials: 

user@password:c123.candidate.11.mongolayer.com:someport/somename

Port : 10952
And on the default database im using the name of the db which is something like : test123.

Every time I click on refresh It says  "Connection failed".

**Comment by achtan** [comment]
Hi, in current version you can specify whole Mongo URI, check it out :)
