### ISSUE TITLE
double colon in host identifier

### ISSUE THREAD

**Issue by myknbani** [DrMongo/DrMongo#105]
I get this error on a recently cloned version of DrMongo when I try to view any collection.

```
Exception while invoking method 'getDocuments' Error: double colon in host identifier
```

**Comment by JeremyBYU** [comment]
Same here I just made this issue as well.

**Comment by myknbani** [comment]
I'll just close this and refer to #106 .

**Comment by spacenergy** [comment]
![2015-12-02 18-26-46 drmongo node node](https://cloud.githubusercontent.com/assets/2149707/11530855/4433af72-9922-11e5-9604-11cc3759fe84.png)
