### ISSUE TITLE
ObjectID support

### ISSUE THREAD

**Issue by JeremyBYU** [DrMongo/DrMongo#110]
This is the error I'm getting in the console: Meteor does not currently support objects other than ObjectID as ids.

Im using [winstondb](https://github.com/winstonjs/winston-mongodb) for logging to a collection.  This way when I log it can go to the console and also be persisted.  It seems that when it creates a document it makes an ObjectID('something') as the _id field (like most other mongodb databases do) instead of just the random string that Meteor does. 

I was under the impression that meteor could still function with this type of object Id. If so it would be great if you could support it in your frontend.

Meanwhile I'll see if I can tell winston to just use strings instead of object ids.

Thanks!

**Comment by tothradoslav** [comment]
Trying to find the problem, but success so far. I have created a temporary solution, which transforms the IDs into strings and shows them, however, this will cause problems updating documents.

This is only in developement branch for now.

**Comment by JeremyBYU** [comment]
Cool I will give it a try. Thanks!

**Comment by JeremyBYU** [comment]
Seems to be working for me.  Thanks.

**Comment by achtan** [comment]
ObjectID support is implemented, check it out! :)
