### ISSUE TITLE
tabs ... 

### ISSUE THREAD

**Issue by mgrivera** [DrMongo/DrMongo#111]
Is there a way to open several tabs? it would be useful to open more than one collection at the same time. 

Maybe I didn't see the correct option, but it seems now you have to open the app serveral times to open several collections at the same time ... 

Many thanks for the great app ...

**Comment by achtan** [comment]
hi, having custom tabs in a browser app is not a good approach, that's why we didn't implemented any custom tabs. 

So yes you are right, you can just open several browser tabs and brows multiple collections or even databases at same time

**Comment by mgrivera** [comment]
Hi @achtan and thanks for your answer. I guess you are correct in your reasoning. I'll have this into account next time I use DrMongo. 
Thanks again for your prompt answer and keep the great work ...
