### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by boustanihani** [DrMongo/DrMongo#122]
I am getting the following error right after choosing a connection =>

```
Exception in template helper: TypeError: Cannot read property 'name' of null
    at Object.<anonymous> (http://<my-server>/app/client/templateHelpers.js?78f7cb0a6e053cd469eeee4e27c3eb4719eaa31a:60:26)
    at http://<my-server>/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2986:16
    at http://<my-server>/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1650:16
    at http://<my-server>/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3038:66
    at Function.Template._withTemplateInstanceFunc (http://<my-server>/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3671:12)
    at http://<my-server>/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3037:27
    at Spacebars.call (http://<my-server>/packages/spacebars.js?1aedcc2aa3ae9ff5d860d73516110cedd77c033e:167:18)
    at Spacebars.mustacheImpl (http://<my-server>/packages/spacebars.js?1aedcc2aa3ae9ff5d860d73516110cedd77c033e:104:25)
    at Object.Spacebars.mustache (http://<my-server>/packages/spacebars.js?1aedcc2aa3ae9ff5d860d73516110cedd77c033e:108:39)
    at Template.DatabaseDashboard.HTML.DIV.HTML.H4.HTML.A.href (http://<my-server>/app/client/views/DatabaseDashboard/template.DatabaseDashboard.js?e6cbfb67b5846b3c87cfa4d74107d220be4c8e24:30:24)
```

Check: https://github.com/DrMongo/DrMongo/blob/fade48ae50746b886db0936972cfcf6ef12bbbad/client/templateHelpers.js#L52

```
Template.registerHelper('pathForConsole', function (params) {
  params = params.hash || {};
  const data = {
    database: params.data.name, // TypeError: Cannot read property 'name' of null
    connection: params.data.connection().slug
  };

  return FlowRouter.path('Console', data);
});
```

**Comment by achtan** [comment]
hi, on which page you see this error? and how is your mongo URI looks like?

**Comment by boustanihani** [comment]
I get this error when I click on a defined connection directly after the connection page is displayed.

This is how my URI looks like:

```
mongodb://<user>:<pass>@<server>:<port>/<database>
```

**Comment by achtan** [comment]
can you try this connection: `mongodb://drmongo:drmongo@ds061454.mongolab.com:61454/drmongotest`

you will get this error `Meteor does not currently support objects other than ObjectID as ids` on documents list, but at least it will load the database and related collections

**Comment by boustanihani** [comment]
Just did, error persists, I am also getting the `Error: Meteor does not currently support objects other than ObjectID as ids` but the `TypeError: Cannot read property 'name' of null` is still there...

**Comment by achtan** [comment]
hmm that error `TypeError: Cannot read property 'name' of null` is strange... I just installed current master and don't see that error... try reinstall DrMongo pls

**Comment by boustanihani** [comment]
just did a fresh git clone... error still there...

**Comment by tothradoslav** [comment]
We are currently rewriting the code in React and this is not occurring to me at all now. So this might have been removed. The react branch is still in progress, I do not suggest using it, yet.
