### ISSUE TITLE
Connection failed error, when connecting to fresh meteor application

### ISSUE THREAD

**Issue by dariuszsikorski** [DrMongo/DrMongo#123]
I have two apps:
DrMongo on http://localhost:3040/
and test on http://localhost:3000/

when i try to connect to: mongodb://localhost:3000
Connection is failed with red communicate

console output: http://pastebin.com/raw.php?i=w5ebYuVD
os: Win7 64bit fresh install

Any suggestions?

**Comment by achtan** [comment]
if your meteor app is running on port 3000 than mongo server for app is on port 3001
more info: https://github.com/DrMongo/DrMongo#connecting-to-meteor-database
