### ISSUE TITLE
DocumentsFilter - UI update

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#134]
- these icons http://grabberapp.com/uoiqem should be moved where we had the paging buttons previously
- this means at the end of filter row - after the input

**Comment by achtan** [comment]
good idea

**Comment by tothradoslav** [comment]
Another idea, maybe going toooo far, but should be considered:
- http://grabberapp.com/zc2nzd
- what if the h1 (name of collection) would be completely removed and thus that entire "row" could be gone
- only the filter row would stay
- then all we have to do is find a place for the "add document" and "collection settings" button, maybe like this: http://grabberapp.com/fk7dxq but with button separators
- finally, the top (blue bar) should then stay sticky, as it would be very small in height

**Comment by achtan** [comment]
not sure if it's necessary... that h1 is a part of the design, and I dont see the reason to remove h1...
and in the future new features will be implemented => new action buttons, so we need this extra free space

minimal design is good, but it have to be also nice!
