### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#149]
We would like to have a new logo for Dr. Mongo and would appreciate any designer's help. Credits will be given :) Thanks.

**Comment by yra99ary** [comment]
@tothradoslav 
I would like to help you.
What you want it to look like?
Can you show me link to references or similar things.
Thanks.

**Comment by tothradoslav** [comment]
@yra99ary Thanks!
We do not have any specific ideas, but the logo should follow these:
- simple :)
- related to databases and / or mongodb
- combined with something related to doctors / medicine :)

We appreciate any help!

**Comment by JDReutt** [comment]
![drmongo](https://cloud.githubusercontent.com/assets/6819604/13867968/c503aa14-ec9a-11e5-93f2-f2596a7da740.jpg)

let me know if you like it! 
- Original Source: "Stethoscope by John Vollmer from the Noun Project" 
  https://thenounproject.com/term/stethoscope/7129/
  http://creativecommons.org/licenses/by/3.0/us/
- Mongo-fied by Joe Reutt @jdreutt

**Comment by fireportx1** [comment]
@tothradoslav 
![drmongo](https://cloud.githubusercontent.com/assets/3442697/13995574/a296d3a8-f121-11e5-8668-ebabefb7e501.png) great product btw!

**Comment by fireportx1** [comment]
![drmongo2](https://cloud.githubusercontent.com/assets/3442697/13997044/28f5a96e-f128-11e5-83a5-6d3cab562fff.png)
@tothradoslav  another variation while i had some time ;)

**Comment by achtan** [comment]
@JDReutt @fireportx1 thx for help, we will let you know soon witch way we wanna go

**Comment by tothradoslav** [comment]
Hi,

We decided to go with @fireportx1 's last version. Thank you both guys for the effort. 

@fireportx1 could you please send us the logo in a few "'usable" formats. Ideally without background, too, so we can use it on the site, in the app, etc.

Also, please let us know what you'd like to get in return. Shall we mention you somewhere? Anything particular?

**Comment by fireportx1** [comment]
@tothradoslav thanks! I will prepare a full set of versions so they can be used across different scenarios. Also i will list the fonts incase you wish to keep a style guide later for the app & website. Ideally a credit and link to my portfolio if thats possible?

**Comment by achtan** [comment]
hi @fireportx1 is your offer still standing?

**Comment by fireportx1** [comment]
@achtan wow forgot about this one, let me grab the files and get them over to you.. do you need any other ui work done?

**Comment by achtan** [comment]
thx man, any help is welcome!
