### ISSUE TITLE
hide ID field?

### ISSUE THREAD

**Issue by dcsan** [DrMongo/DrMongo#150]
is there a way to not have the ugly IDs in the table view?
i tried un-pinning that field but it seems to have no effect.

![image](https://cloud.githubusercontent.com/assets/514002/12691309/90e20bf2-c69f-11e5-9fdf-b52d5a90a51c.png)

**Comment by achtan** [comment]
hi, now you can toggle ID's length in table view
<img width="460" alt="screenshot 2016-04-05 20 37 26" src="https://cloud.githubusercontent.com/assets/1048212/14293830/9a82b6da-fb6e-11e5-9076-93e135701e19.png">

but u cannot completely remove _id column... i hope this will help
