### ISSUE TITLE
I miss the refresh button!

### ISSUE THREAD

**Issue by rijk** [DrMongo/DrMongo#155]
Please bring it back :) It is invaluable when switching projects often. At this moment, I cannot get the database to refresh the collection list. I usually have to wait for the app to crash because it can't find one of the tables, and then restart Meteor.

**Comment by achtan** [comment]
hi, do you have the latest version? 
cuz collection list is fetched from DB on every page load (hard refresh)

**Comment by rijk** [comment]
Yep. I'm on the very latest version. Now, I started it up after a week not using it, went to `localhost:3040` and the collections of a Meteor project I haven't run for days are still there. And the console is flooding with errors. (" Error: Collection [meteor.addresses] not found." etc)

**Comment by achtan** [comment]
ok we will fix this.
Temporary workaround is to create new connections in DRM for every project (or even run every project on different port)
