### ISSUE TITLE
Does not remember browser history on all "searches"

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#157]
- if I type a new query (selector) and submit
- then I type another one and submit
- then I click "back" in browser history, it DOES NOT go to the previous page, but several "steps" back
- seems like it only remembers the last "step" for each collection

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
