### ISSUE TITLE
Project abandoned? Lots of error when perform meteor update.

### ISSUE THREAD

**Issue by lesliechw** [DrMongo/DrMongo#167]
Is this project abandoned?

After clone the project files, then run meteor update, lots of error.

Any advice?

**Comment by achtan** [comment]
Hi, we don't invest much time into this project right now. But we are using it on daily basis. So it should work just fine.

don't run `meteor update` only clone and run

**Comment by lesliechw** [comment]
Ok thanks for the info.

**Comment by achtan** [comment]
let me know if you have any other issues

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
