### ISSUE TITLE
complex and more versatile filters

### ISSUE THREAD

**Issue by zeroasterisk** [DrMongo/DrMongo#172]
I have reviewed `processFilter()` and see the fancy date selectors you've added... _(kudos)_

but while experimenting with the package, it doesn't seem to do support doing advanced filtering - it's only got basic string searching and date handling _(both well done)_

are you planning on supporting full mongo queries as passthroughs?

are you planning on supporting other types of custom "quick" searches like `{myfield: #exists}`?

**Comment by achtan** [comment]
hi, good idea with that `{myfield: #exists}`!

what you mean by "full mongo queries as passthroughs" can you provide some exmaples

**Comment by zeroasterisk** [comment]
An example might be the _long_ form of the same: `{myfield: {$exists: 1}}`
Or a more complicated query: `{somecount: {$gt: 5, $lt: 9}}`
Or a specific regex: `{name: /j(im|oe|ames)/gi}`
Or... more likely, a combination of several

**Comment by achtan** [comment]
inspiration: https://github.com/allmas-tn/mongo-dql

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
