### ISSUE TITLE
Each document row should contain the order number

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#42]
- starting with 1
- on page 2 starting with (countPerPage*pageNumber + 1)

**Comment by achtan** [comment]
why?

**Comment by tothradoslav** [comment]
Because it shows you where you are - page. More obvious than paging. Paging is control. This is info. Definitely needed for advanced use

**Comment by tothradoslav** [comment]
How could this be done? We need to move the skip / limit internal params to CurrentSession and then add an "index" atribute to all documents, but this is risky, cause what if document contains "index" atribute?
