### ISSUE TITLE
Paging issues

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#57]
1. [x] i can go to page 3 if there are only results for 2 pages
2. [x] when I am on page one and click prev (or first), the page reloads, but ideally these links should be inactive. Same applies to next / last: they should be inactive when "not available"
3. [x] results count should say "21 docs", it's not obvious like this
4. [x] maybe we should completely remove paging links if there are results only for this page

**Comment by achtan** [comment]
"results count should say "21 docs", it's not obvious like this"
imho its not necessary to add label to number... we don't use any labels for buttons as well.
As we said before, if you use app frequently its become obvious what button is for what action

**Comment by tothradoslav** [comment]
-[ ] set common class for all pagination buttons
-[ ] inactive opacity 0.2, cursor not-allowed
-[ ] hover lighter color
