### ISSUE TITLE
Make the values in-line editable so you don't have to click off to the ace editor view

### ISSUE THREAD

**Issue by JackAdams** [DrMongo/DrMongo#78]
In doing this, though, I understand that you lose the nice click-on-an-id-and-it-takes-you-to-the-doc feature (which is my absolute #1 selling point for DrMongo).

Unless there was a little `fa-external-link` icon beside the `_id` type field you could click to go and see the other document. :-)

**Comment by tothradoslav** [comment]
This is a great point. There are 2 solutions in my head:
1. add a "pencil" icon to each value to edit it in-line (thus leaving the click-id functionality)
2. do the inline editing only on non-id-resembling-values - why would you want to change an _ID anyway?

1 is better, but I'm afraid of all the icons "flying around" in DrMongo :)

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
