### ISSUE TITLE
Desktop App 

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#87]
Sources:
https://forums.meteor.com/t/a-meteor-desktop-application/291/34

https://medium.com/@guidouil/cross-platform-desktop-apps-with-meteor-and-electron-5355eb9e351#.43gn14xr7

http://electron.atom.io/

https://github.com/sigmeus/meteor-desktop-app

**Comment by sasikanth513** [comment]
+1

**Comment by vNakamura** [comment]
There is a package called Electrify that makes it really easy to build an Electron app:
https://atmospherejs.com/arboleya/electrify

I tried packaging DrMongo and it works fine on OSX.

**Comment by achtan** [comment]
that's awesome! thx for help! we will look into it...

**Comment by etyp** [comment]
+1

**Comment by achtan** [comment]
hi @vNakamura i tried also, but i'm getting this error: https://github.com/arboleya/electrify/issues/41
do you have any suggestions how to solve this issue?

**Comment by vNakamura** [comment]
I tried packaging again and got the same error.
That's odd cause I had no problem back in January when I suggested electrify.

Maybe the node version? I used to have a v0.12 node installed and updated to v5 recently.
I'll make some tests

**Comment by achtan** [comment]
hi @vNakamura we updated to latest meteor (1.5) 
are you still interested in creating desktop app ?

**Comment by vNakamura** [comment]
Oh, sorry. It's been a while since I last worked with meteor.

**Comment by achtan** [comment]
we're already working on a new desktop app, stay tuned

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
