### ISSUE TITLE
Feature request: Drop all documents

### ISSUE THREAD

**Issue by JuanCrg90** [DrMongo/DrMongo#93]
Hi. is it possible add a button for drop all the documents in a collection like Robomongo?

Do you have a TODO list for contribute?

Cheers.

**Comment by achtan** [comment]
hi, good suggestion!

Currently our todo list is issue list... so if you want to help us u can just pick some isse :) and that would be awesome!

**Comment by JuanCrg90** [comment]
Excellent Thank you. :smile:

**Comment by achtan** [comment]
done
